### ISSUE TITLE
smoke test needs java to run builder

### ISSUE THREAD

**Issue by spydmobile** [WISE-Developers/WISE_Application#30]
install java and execute:

java", "-jar", "/usr/bin/PSaaS_Builder.jar"

use this:
```
- uses: actions/setup-java@v3
  with:
    distribution: 'temurin'
    java-version: '17'
    check-latest: true
- run: java HelloWorldApp.java
```
